### ISSUE TITLE
Compatibility certification request for Weld

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/injection-spec#3]
- [*] Organization Name ("Organization") and, if applicable, URL\
  Red Hat, Inc., http://redhat.com
- [*] Product Name, Version and download URL (if applicable)\
Weld 2.4.8.Final, https://weld.cdi-spec.org/download/
- [*] Specification Name, Version and download URL\
 Jakarta Dependency Injection 1.0
- [*] TCK Version, digital SHA-256 fingerprint and download URL\
http://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip, b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f
- [*] Public URL of TCK Results Summary\
https://github.com/jakartaredhat/weld-inject-tck/wiki/Jakarta-Dependency-Injection-1.0-TCK-Results
- [*] Java runtime used to run the implementation\
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
- [*] Summary of the information for the certification environment, operating system, cloud,\
iMacPro, OSX 10.14.4
- [*] By checking this box I acknowledge that I accept the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [*] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
The TCK URL is stale. I'd guess that the SHA256 is no longer accurate. Looking at the Jenkins job, it appears to have been rebuilt. I'd recommend pushing your proposed final release to more stable location, perhaps the Project download folder at download.eclipse.org.

**Comment by starksm64** [comment]
> The TCK URL is stale. I'd guess that the SHA256 is no longer accurate. Looking at the Jenkins job, it appears to have been rebuilt. I'd recommend pushing your proposed final release to more stable location, perhaps the Project download folder at download.eclipse.org.

The latest build is in the http://download.eclipse.org/ee4j/cdi/ directory.

**Comment by edbratt** [comment]
Final TCK link is 
https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip
SHA is correct.
Update the TCK link and this looks good to go. Accept and close? (PS, for consistency, it would be nice to update the TCK summary page with this link as well.)

**Comment by starksm64** [comment]
The TCK links have been updated to the final promoted version.
